name: flutter_showcase
description: Showcase your flutter project
version: 0.0.6
homepage: https://github.com/jamesblasco/flutter_showcase

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.8.1
  fluid_layout: ^0.1.0
  equatable: ^1.1.1
  dart_style: ^1.3.4
  analyzer: ^0.39.6
  _fe_analyzer_shared: ^2.1.0
  args: ^1.6.0
  yaml: ^2.2.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  flutter_driver:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/
